### ISSUE TITLE
Renaming the LegacyApplication#context to jmeContext

### ISSUE THREAD

**Issue by Bekreth** [jMonkeyEngine/jmonkeyengine#1024]
A large number of opensource frameworks maintain internal contexts, and almost all of them use a globally accessible variable named `context`.  The `LegacyApplication` should update the name of its `context` variable to be `jmeContext` as well as updating all classes to refer to it by its method `getContext()`.  It would also be preferential for `getContext()` defined in `Application` to be updated to `getJmeContext()`.

**Comment by pspeed42** [comment]
What is the benefit of doing this?

**Comment by tlf30** [comment]
I do not agree that `context` should be renamed. I see no benefit as there are _almost_ no situations where a naming conflict can occur, and in the situations where a conflict could occur would be caused due to poor design, or extreme edge cases. 

Secondly, it would break many applications that are currently using JME, and break backwards compatibility. 

Can you provide a situation where it would be required to have `context` renamed?

**Comment by pspeed42** [comment]
Yes, I also agree there is no need for the change... which is why I was asking why it was needed.

"So my IDE doesn't recommend it to me..." is not a valid excuse, for example.
