### ISSUE TITLE
TestCcd broken for jme3-bullet

### ISSUE THREAD

**Issue by stephengold** [jMonkeyEngine/jmonkeyengine#1043]
In current `master` branch, `jme3test.bullet.TestCcd` behaves differently with `jme3-bullet` than it does with `jme3-jbullet`:

The green projectiles (generated by clicking the left mouse button) have `setCcdMotionThreshold(0.1f)` and are launched at 40 wu/sec velocity. When they're fired toward the obstacle (which is 0.1 wu thick) in `jme3-jbullet`, they consistently bounce off the obstacle.

In `jme3-bullet`, however, the behavior seems to depend on where the projectile collides with the obstacle: in some locations the projectile bounces back, in some it's deflected but passes through, and in some the projectile seems to pass through without deflection.

**Comment by riccardobl** [comment]
It seems that passing a value grather that 0 to setCcdSweptSphereRadius makes the test behave as expected (the default value is 0), im not sure about what having it set to 0 mean for bullet..

**Comment by stephengold** [comment]
I tested some old releases. The test has been broken since at least JME 3.1.0-stable.

**Comment by stephengold** [comment]
The test works with Minie v0.2.10 but not with Minie v0.2.9. This leads me to suspect this issue is related to collision margins, which default to 0 in Minie v0.2.9 (and in all current JME releases). Minie v0.2.10 changed the default collision margin to 0.04 .

**Comment by stephengold** [comment]
See issue #901.

**Comment by stephengold** [comment]
Increasing the collision margin of the obstacle to 0.0001 is sufficient to resolve this issue. I'm undecided whether to modify `TestCcd` or address the larger issue #901 in `CollisionShape`.

**Comment by stephengold** [comment]
So far we have 3 possible fixes:
 (1) increase the collision margin of the obstacle in `TestCcd`
 (2) implement a default collision margin >0 in` jme3-bullet`
 (3) increase the swept-sphere radius in `TestCcd`

@riccardobl: Which fix do you think is best for the project?

**Comment by riccardobl** [comment]
I'd say that we should definitely fix it by increasing the default margin, since as you reported in issue #901 the official documentation advise against using 0 margin.

**Comment by MeFisto94** [comment]
Definitely against 1, because in my game, ccd doesn't work either. thus the real solution probably is 2.
Regarding 3: I could swear I was having troubles with a set swept-sphere radius. Probably only under steep angles and high speed, but still.

Edit yep:
```java
cc.getRigidBody().setCcdSweptSphereRadius(0.35f * 0.1f);
cc.getRigidBody().setCcdMotionThreshold(0.35f/* * 0.125f*/);
```
With these settings passing objects was almost impossible at least but it still worked. Maybe we might need a test case which would also expose this problem when having a SweptSphereRadius set? This is probably resolved with 2 as well though.

**Comment by tlf30** [comment]
@stephengold I say go for 2. It would be better to fix the issue now, and not continue to apply band-aids to everything that is broken.

**Comment by stephengold** [comment]
My only concern with fix(2) is that it might break existing apps---if they expect `margin=0` and get `margin=0.04`. Ideally, the margin would be set based on the size of the collision objects: when the physics-space units are meters, 0.04 is fine for driving simulations but problematic for simulating ocean liners or [knucklebones](https://en.wikipedia.org/wiki/Knucklebones).

**Comment by riccardobl** [comment]
Most games don't need accurate collisions anyway, if 0.04 is the default for bullet, i think it should be for us too.

**Comment by tlf30** [comment]
As for it breaking existing apps, any time that a key library gets an update, there are going to be things, just like this, that have changed in order to fix bugs, or add new functionality. I do not think it is bad to have backwards compatibility broken a little between major updates. Especially if this was made part of v3.3. App devs know that they are going to have to make minor changes to their code during major updates for supporting libraries.

**Comment by stephengold** [comment]
Closing this issue as a duplicate of #901.
