### ISSUE TITLE
Proposal: Adopt a standard code format

### ISSUE THREAD

**Issue by riccardobl** [jMonkeyEngine/jmonkeyengine#1056]
I know this might raise some eyebrows, but hear me out, the code style in jme is pretty much the one suggested by google, with some inconsistency https://google.github.io/styleguide/javaguide.html#s4-formatting .

I think we should at least consider adopting  it officially either in an incremental way or with a single formatting commit, in one of the future major releases.

This would provide a  baseline and a quick way to fix formatting issues in PRs.

**Comment by pspeed42** [comment]
I'm kind of on board with this.  In the long run, it turns out not to matter too much to have a detailed style guide but it can make the bulk of code easier to read.  

I think incremental may be best for at least one reason: using the "blame" option in git is waaaay easier if there aren't giant formatting commits.  GIT doesn't make it easy to jump to the previous event for some line of code (as far as I know).

We generally (sort of) adopted a "when in Rome" style policy where when one is editing surgically, try to keep the style of the file they are in... or at least don't reformat the whole file.  Reformatting sort of == "I'm taking over responsibility for maintaining this file".

I'm not sure what the final solution should be.

I think for new code we definitely should point someone to a style guide.  The google one is nearly perfect except the +2 space indent thing.  (There is only one other small point I disagree with but I'm in the minority on this with the rest of the world.  "if (condition)" versus "if( condition )")

Anyway, we should be careful to reject contributions with only small problems that don't really matter but should definitely have some minimum standards.  Like, I'm not going to reject code because the array initialization is eight-space indented instead of four but I will certainly reject CapitilizedDotNetStyle method and variable names that look like class names.  Or for sure reject empty catch blocks, throwing NullPointException on purpose, etc..  Things that really matter to code quality over time.

**Comment by stephengold** [comment]
Because I use the Netbeans-based IDE, I find it convenient to use the Netbeans formatter with default settings: in new code I indent each block 4 spaces and put a space after the "if" keyword.

Being a traditionalist, I limit my lines to 80 characters.

Like Paul, I try to follow the "when in Rome" policy for surgical edits.

**Comment by tlf30** [comment]
I think this would be great. At work we have a netbeans format config that allows us to right click -> Format, and our company coding format gets applied. That way when people forget and don't format their code right, netbeans will auto-fix it. It would be nice to have for JME.

**Comment by Ali-RS** [comment]
I also use the default code formatting style in Netbeans both in my own codes and when making PR for JME .

**Comment by Ali-RS** [comment]
Unfortunately there is no Google Java Format plugin for Netbeans, but there are gradle/maven plugins availble. https://github.com/google/google-java-format 
Maybe we can use a [server side git hook](https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks)  to use https://github.com/maltzj/google-style-precommit-hook ?

**Comment by empirephoenix** [comment]
I think serverside formating is probably the way to go, it keeps the initial effort to contribute low, while offering the benefits (and does not enforce some more or less crappy ide plugin)

**Comment by pspeed42** [comment]
In projects where formatting was auto-forced on the server, we always lived to regret it.  The auto-formatters tend to nuke all formatting that most would consider optional.  For example, sometimes an extra line feed really does make sense, or lining up indents on non-standard boundaries, etc..

...and the looser the auto-formatter, the more it lets through that you'd legitimately want formatted.  It's better if humans format the code.  The point of formatting is to make it more readable and an autoformatter has no idea what "more readable" is.

It's also not really important enough to be draconian about it, in my opinion.  Beyond some core values, I'm ok with some flexibility.  Gov't mandated religion always seems like an ok idea when it's your religion that's being mandated, for example.

**Comment by riccardobl** [comment]
Could something like this work for netbeans: http://plugins.netbeans.org/plugin/70382/eclipse-java-code-formatter-eclipse-neon-4-6-1a ?

Personally, i don't really have a strong preference for the style, but i think we should choose one which have configurations available for at least a couple of the most widespread ides.

**Comment by riccardobl** [comment]
This seems to be the same as the default netbeans style: [sun_coding_style.xml
](https://raw.githubusercontent.com/opendaylight/vtn/master/manager/common/sun_coding_style.xml)

Eclipse formatting profiles can be used also in virtual studio code and idea ( [with this plugin](https://plugins.jetbrains.com/plugin/6546-eclipse-code-formatter) ).

**Comment by tlf30** [comment]
I noticed while going through the jme-network project that much of the code was opening bracket on new line: 
```
public void someFunction()
{
...
}
```

It would be nice to have a PR where someone just ran the netbeans formatter on the entire jme project just to clean things like this up a little.

**Comment by pspeed42** [comment]
Somewhere, I thought I mentioned that I did that on purpose... but it may have been on discord.  (I can speak several formats fluently.)  I used that one to distinguish the new code from the old code as I was rewriting it.  By now it probably does deserve to be reformatted, though I always wished to go back and rewrite the crappy serializer stuff.

**Comment by Ali-RS** [comment]
I am agree with reformatting with Netbeans formatter (I always do this before making a PR) but we also should somehow force contributors to use the standard formatting too, for example see this PR: 
It uses an style which is not used in JME and also is not recommended.

https://github.com/jMonkeyEngine/jmonkeyengine/blob/32503eea5b0556f89e72ba82a8524b0d6c50d961/jme3-core/src/main/java/com/jme3/renderer/Camera.java#L1488

**Comment by louhy** [comment]
> It would be nice to have a PR where someone just ran the netbeans formatter on the entire jme project just to clean things like this up a little.

I a formatting hawk but also frequently rely on Git history. It's always tempting to just clean up inherited code, and it's nice at coding-time, but don't forget about Git diffs with old changes. That would become less painful over time, at least. 

I forced myself to adapt to the standard NetBeans formatter years ago out of convenience (sometimes increase the maximum line length because I find 80 harsh), and automatically run that formatter on every save. For anyone not using NB, I guess using that as a standard is a problem, unless all 3 IDEs by chance used the same standard (yeah right). 

Certainly new code should follow a standard, at a minimum, if someone's willing to enforce it... 

As far as using Google's standard, with the frequency they love to make changes to things (not to mention abandon them), I don't trust them anymore. And with the constant Oracle/Google fighting over Java, who knows if that page will even be there long term.

**Comment by pspeed42** [comment]
What is the difference between Google's standard and Netbean's?  I really like the Google standard, personally.

As far as the "don't trust them" stuff, are we really worried about a document disappearing without a single trace on the entire internet?  If so then cut-paste the google style doc and call it the "JME style doc" and be done with it.

**Comment by louhy** [comment]
Couldn't resist a chance at a low blow at Google, not a serious concern. :satisfied:

**Comment by louhy** [comment]
Finally looked at the Google standard. I don't know what the differences are, but apparently I've been working for Google all this time and didn't realize it. 

I use NetBeans standard formatting at work+home so I guess I'm pretty familiar with that, and other than the 80 vs 100 character right margin difference (Google's is larger), I don't notice any big difference.

**Comment by Sailsman63** [comment]
For those concerned that a 'reformat' commit makes things harder to track, git does have some options:
- `git blame -wM` will skip over whitespace and line reordering.
- `git log -L <startline><endline>:filename` give a commit list that affected those specific lines (requires git 1.8.4)

[Credit](https://stackoverflow.com/questions/5098256/git-blame-prior-commits)

**Comment by pspeed42** [comment]
It's through the github web site that it's a pain... and 99.9% of my code history exploration is through the web site.  (Which is unfortunate because on the web site, history cuts off at when we imported from SVN... even though the history is still there I guess.)

**Comment by louhy** [comment]
After doing some cleanup work recently... not sure how I feel about it now. Sometimes comment blocks are structured in a way that the NetBeans formatter will mangle. For example "ASCII art" style diagrams which rely on newline preservation. NB is very aggressive with comment reformatting. But we could turn that off. 

With an incremental approach... 
- Need to deal with a _constant_ flow of distracting format changes for virtually every PR...
- PR author needs to use NetBeans to format, or someone else needs to do it for them 
- Git browsing still a mess for that particular file - no getting around that
- The repo will probably never get near 100% clean formatting 
- Any formatter comment mangling can be found and corrected before merge

With a big-bang reformat...
- Take the bad medicine now, and it'll matter less as time passes
- NetBeans formatter is likely to mangle certain comments (maybe even code) which needs to remain unformatted. If that's not acceptable, every file would need review. Or, don't format comments at all. 
- Might need lots of review at once? 

Doing nothing...
- Some messy code

Status-quo doesn't seem so bad now. If we can avoid the comment mangling, I think I'd agree with @Ali-RS and @tlf30 - just do the big bang reformat and get it over with. 

@pspeed42 Not sure if it uses the options above, but you could try something like GitKraken to browse. Probably you don't want to be bothered with it, but I've used it for a few years and it's faster to navigate than a website, IMO.

**Comment by tlf30** [comment]
I have been meaning to do this, but I have not been home much in the last couple months due to work. I will try to get to this in the next couple days.

**Comment by pspeed42** [comment]
Mass code reformatting is one of those things that feels good because you get to make a lot of changes and it feels like you're being productive.  In the end, it doesn't really change much of anything and will certainly make some files uglier.

Some files ugly now.  Some files ugly later.  Lots of work to end up in the same place while screwing a bunch of other things up in the process.

This is why I lean towards "Do nothing".  If you are taking over maintenance of a particular file then reformat it to the standard if you like.  Else I still say any "let's reformat everything" work's only real benefit is making the person doing it feel artificially productive for a few minutes.

**Comment by louhy** [comment]
@tlf30 This could instead be done with a 4.0 release whenever that happens, but even then it'd probably be best to wait until it's nearly ready, so that you can pull changes in from the current 3 repo. A mass change like this (even if it's targeted) seems like way more trouble than it's worth for your 4 repo, if it were to be done immediately.

**Comment by tlf30** [comment]
@louhy yes, that is probably the best idea. I will add it to the roadmap for 4.0 postwork.
