### ISSUE TITLE
Concurrency issues with Node.java

### ISSUE THREAD

**Issue by Bekreth** [jMonkeyEngine/jmonkeyengine#1123]
I'm running a highly parallelized game and recently ran into issues with children properly attaching to `Node` object due to a `java.lang.IndexOutOfBoundsException`.  Diving into this issue, the core problem is that the `SafeArrayList` is _not_ thread safe, as per the JavaDocs "This list is not designed for threading concurrency".  The documentation also lays out that thread safety is given up as "Optimum usage is when modifications are done infrequently or in batches... as is often the case in scene graph", but the `Node` object doesn't provide batch write options for attaching children.

In lieu of these issues I propose the following
1. `Node` is updated to have `int[] attachBatchOfChildren(SafeArrayList<Spatial> children)`
2. Methods for attaching and detaching children from the node should synchronize on the `SafeArrayList`, or safe version of these methods be added.
3. `SafeArrayList` should be renamed to be more in line with its documented purpose.  Possibly something along the line of `SafeReadArrayList` or `BatchWriteOptimizedArrayList`.

While I can currently solve my issue by synchronizing on my `Node` objects directly, this is a clunky process that blocks all other usage of these objects.

**Comment by pspeed42** [comment]
NONE of the JME scene graph is thread safe.  This is by design.

If you want to attach a bunch of things safely, add them to a ConcurrentLinkedQueue and then add them from the thread that owns the node.

SafeArrayList is called "Safe" because you can modify it while removing.  What you are looking for would be called "CopyOnWriteArrayList" which is already part of the JDK and is thread safe... but expensive.  Naming can get a little extreme otherwise.  I mean, we could call it "CanSafelyAddRemoveWhileIteratingArrayList"... but still someone will get confused.

**Comment by pspeed42** [comment]
Note: Node's child list is not the only thing you will run into if you try to mess with the scene graph from multiple threads.  None of it is thread safe.  Positions, light lists, rotations, modification flags... all of it danger danger danger.

One thread at a time can own a Spatial.  That's a conscious design choice and it's truly trivial to thread around that.
