### ISSUE TITLE
jMonkeyEngine SDK v3.2.3 connects to nbandroid.org

### ISSUE THREAD

**Issue by KenVanHoeylandt** [jMonkeyEngine/jmonkeyengine#1140]
Platform is macOS.
Version is 3.2.3-STABLE.

nbandroid.org is for sale and is hosting ads/malware, which puts users at risk.

This happened on startup and I blocked the requests with my firewall.
During the first 2 visits through a regular web browser, I got a few dozen redirects that ended up in a fake virus/malware warning.

**Comment by stephengold** [comment]
Where did you download this SDK from?

**Comment by stephengold** [comment]
I searched the source repository for the string "nbandroid". The site is referenced in the file "jme3-android\src\com\jme3\gde\android\Bundle.properties". @MeFisto94 can you provide any insight into this issue?

**Comment by louhy** [comment]
Yikes, people on the NetBeans plugin site say the site was closed and another took its place. 

http://plugins.netbeans.org/plugin/19545/nbandroid

Seems like a candidate for an emergency fix in the upcoming release?

**Comment by MeFisto94** [comment]
Thanks for bringing this to our attention!
Insight: NBAndroid was/is the Plugin to support Android Dev in the SDK. There is more information about that on the wiki. I guess we included nbandroid as a plugin download source, which is why it tries to connect. But someone did not pay the bills it seems. 

There is more to that sadly: The SDK currently has issues with Android (because the "SDK" of Android, which was to download emulators and stuff, has changed it's command line syntax). Thus people are using the SDK but then run the project on Android with IntelliJ I guess.

The question now is if we use https://github.com/NBANDROIDTEAM/NBANDROID-V2 or drop Android Support, which would be bad for the SDK. The problem is: Many people who are into Android are probably used to Android Studio aka IntelliJ. 

Also I don't like how you need an installer to install the module, I guess we need to bypass this manually

**Comment by MeFisto94** [comment]
Moved to https://github.com/jMonkeyEngine/sdk/issues/194

**Comment by nickidebruyn** [comment]
Please do not drop Android support.
I am still using the nbandroid plugin as well as the ant android build.
I am building the SDK by pointing it to netbeans8.1 that still support nbandroid.

**Comment by MeFisto94** [comment]
Reporting here as well:
Hotfix one: Go to Plugins -> Settings and Disable or Remove NBAndroid Updates
On a non-fresh install, you have to remove that update source. It won't be added on a fresh install, but it won't be auto-removed.

Note that AS OF NOW this does NOT really do harm though, as the exact URL returns a 403/404 error code and thus netbeans moves on. It could however happen, that someone is using this domain to deploy malware netbeans modules, and as such you SHOULD remove this source.

The next release of the SDK will have NBAndroidV2, I hope this works for you @nickidebruyn (if you have the time to test it out).

**Comment by nickidebruyn** [comment]
Hi @MeFisto94 ,
That is very good news and I would be more than happy to test it.
Thanks.
