### ISSUE TITLE
Forum down?

### ISSUE THREAD

**Issue by mitm001** [jMonkeyEngine/jmonkeyengine#1162]
Is it just me or is the forum down?

**Comment by jayfella** [comment]
Yes it’s down. I’m doing everything I can. Everybody I need to talk to seems to have disappeared. Hopefully someone will respond soon.

**Comment by riccardobl** [comment]
Do you know why it is down?

**Comment by oxplay2** [comment]
who is hosting it currently?, because i dont remember. i understand evertyhing we can do is wait for "people you need to talk to"  ;/

**Comment by jayfella** [comment]
Yes I know why it’s down and I know how to solve it, I just need permission elevations.

**Comment by oxplay2** [comment]
Just to let you know, if there are a lot of problems hosting it, there is chance "we" might be able to host it.(on own servers).

sites already run are like almost 100% uptime.

access could be provided.

but its only if you guys really require help with hosting.

**Comment by jayfella** [comment]
I spent half the day getting the jmonkeystore forum to work. Feel free to sign up there. I'm not sure if/when the current forum will be available.

https://hub.jmonkeystore.com/

**Comment by riccardobl** [comment]
I don't think it's a good idea to have 2 forums.

**Comment by jayfella** [comment]
Its not 2 forums. One is for jmonkey and the other is for the store. The Jme forum doesn’t work right now and I’m not sure when it will be up. I can’t get in touch with anyone.

**Comment by oxplay2** [comment]
jMonkeystore should just have category in main forum, i agree with Riccardo.

Still no word from people who can help you solve hub forum issue?

**Comment by jayfella** [comment]
Guys I don’t think there is a forum anymore. From what I know: 

We are hosted on digital ocean. We were a part of their open source sponsor program and that expired. I contacted them twice to renew it and got no response. During that time the bill wasn’t paid and whilst I have all kinds of ssh and backend permissions, I do not have permission to pay the bill. I contacted everyone that did have permission time and time again to the point of annoyance and got no response, so I couldn’t pay the bill myself. I still haven’t got a response. I tried to contact digital ocean and explain the situation but they again didn’t even bother responding. Which basically means I was the only active member of the server team with no permission to solve the problem and despite shouting from the roof could not pay the bill. 

So. As of now: Digital ocean invoices are sent out on the first of every month. You have 21 days to pay. If you don’t pay by then the droplet is purged and the data is available for 72 hours until deleted. 

We do have forum backups, but again I do not have access. The issue now is that it’s not just the backup but the entire configuration of the server gone. It was quite a complex setup. I know because I was part of the team that set it up. 

I don’t know what happens now. At this point it’s pretty clear to me that that’s the end of that. I hope I am wrong, but I tried everything and got absolutely nothing except white noise.

**Comment by jayfella** [comment]
I should also say that the asset store was sponsored by members of the community and is still available, along with a forum. It will continue to remain and developed until such time you guys stop sponsoring it. Feel free to use that forum as normal if you so desire. That is all I can do.

**Comment by neph1** [comment]
There's also the Slack channel, although it's pretty desolate at the moment. What about setting up a free forum from one provider or another?

**Comment by riccardobl** [comment]
https://free.discourse.group/ :thinking:

**Comment by jayfella** [comment]
Set one up if you like. I am not the owner of jmonkey. All I'm saying is that in light of the situation that the asset store is still there so long as the sponsorship warrants it.

**Comment by grizeldi** [comment]
What riccardo found might be it, but the problem atm is that we don't have a way to get the current forum data if I understand correctly.

**Comment by jayfella** [comment]
And that if it gets the same traffic as the hub, it will exceed traffic in less than 10 days.

**Comment by riccardobl** [comment]
> get the current forum data

This is the priority, who has it?
Was the DO droplet purged or are we in the 72 hours period?

**Comment by jayfella** [comment]
It's hosted on AWS. @shadowislord has the keys. I've tagged him in this conversation already, I've pinged him multiple times on slack. I've contacted every team member that has possible access multiple times over multiple days.

**Comment by riccardobl** [comment]
>  The 72 hour period ends in less than 11 hours

And you don't have any way to access the data in this time, correct?

**Comment by jayfella** [comment]
Hrm. Hang on.

**Comment by jayfella** [comment]
Praise the lord they gave us sponsorship.

**Comment by jayfella** [comment]
The server should be up in moments.

**Comment by neph1** [comment]
I appreciate the work you put into this, jay. This whole hosting issue keeps popping up every now and then. Can we prepay, or otherwise make sure it doesn't happen again (or so often?)

**Comment by jayfella** [comment]
From what I can see in the security logs it says we have a "lifetime value" billing update about 5 hours ago, so I guess we're fine for now.

**Comment by skyebook** [comment]
Hi folks, back on personal email after work travel this week. Glad this is resolved. Unfortunately I don’t have any Digital Ocean access for us.. I think my official webmaster tenure ended when we finally got the server into the cloud and out of a university closet in New York some years ago. For future renewals through DO is there any info from them on deadlines to reapply, etc?

**Comment by mitm001** [comment]
Its now lifetime but can contact @jayfella in case he needs something from you.
