### ISSUE TITLE
Buildscript issue

### ISSUE THREAD

**Issue by Ali-RS** [jMonkeyEngine/jmonkeyengine#1207]
Recent cleanup in @riccardobl commit https://github.com/jMonkeyEngine/jmonkeyengine/commit/8a6bd1947cca1814e0139353ca629dd88faafc00  (on "configureVersionInfo" task)  which is part of PR #1190 makes local installing of maven artifacts from master to use the commit hash name for pom versioning instead of "-SNAPSHOT". 

This would be painful for those who are building the engine from source :(

**Comment by riccardobl** [comment]
There is a problem with using "-SNAPSHOT" for local builds.
Let's say you have master-SNAPSHOT, where is this master branch from? The local repo? The remote repo? A fork? :man_shrugging: 

That's why I modified it to use only commit ids and tags.  

If you want a custom/known version name you could add a tag and build
```console
git tag localBuild
gradle build install
```

But i see this might not be very flexible.

I think the best approach to fix this would be to add a property to define a custom version name eg.
```console
gradle build install -PversionName="local-SNAPSHOT"
```

What do you think?

**Comment by pspeed42** [comment]
But it seemed to work before somehow, eh?  At least when I built from 'master', it would get installed as 3.3-snapshot... and it's something I made a mental note to make sure to 'upgrade' to 3.4 when I create the 3.3 branch.

I'm also not sure why it matters "where it came from" since generally SNAPSHOTS will only be in your local repo because you built them.  Most official places won't even let you upload them.

**Comment by riccardobl** [comment]
If i clone the current 3.3 repo, i make a modification and i build it, am i building the 3.3 snapshot? The 3.4 snapshot? the 3.3.1 snapshot? What if i want to test the new commits without overwriting the dependency for my actual project? What if i want two projects to be based on two different "master-SNAPSHOT"?

**Comment by pspeed42** [comment]
I agree there should be a way to specify a custom version but there should also be default behavior that can be used as dependencies without having to change the dependency every time you git pull.

Right now, if you check at master and do a gradle install with no other configuration, I think it should default to install 3.3-SNAPSHOT.  When we branch 3.3 then master should install 3.4-SNAPSHOT by default.

...because these are what master represents at those times.

**Comment by riccardobl** [comment]
The old default behaviour was to have
`major.minor.patch-SNAPSHOT `
for the master branch
and 
`major.minor.patch-branch-SNAPSHOT`
for everythin else.

It seems you are proposing something different, that is
`major.minor-SNAPSHOT` 
for every branch, or
`major.minor-SNAPSHOT`  for master
and `major.minor-branch-SNAPSHOT`  for the other branches? 


I think having the commit id by default and a configurable version is better since it removes every sort of confusion, but i'm ok also with this.
We will need also an useCommitsAsVersion=true property to be used in the CI, since it publishes maven libraries within the github actions artifacts, and having all the libraries named with the same version name for every build wouldn't lbe very practical

**Comment by pspeed42** [comment]
For your last paragraph, are you talking about the builds that are done to check commits and merges or the builds that are done for releases?

**Comment by riccardobl** [comment]
For every build. I'm talking about what you can find here
https://github.com/jMonkeyEngine/jmonkeyengine/commit/2c6161ecd8e7d7ced3752724b220feca5aabced1/checks?check_suite_id=279113659
between the artifacts (top right) stored for 90 days.

**Comment by pspeed42** [comment]
Most projects, if you check out a specific version then it will build that version but if you checkout 'master' then it will build a -SNAPSHOT version.  In those same projects, I guess this is usually not automatic and part of the release process is to roll the versions in the various files.

But it's an important user experience because -SNAPSHOT is a special marker that causes build tools to bypass any local caching.

How it should be is that if I check out JME master then do a gradle install, I (right now) should get 3.3.0-SNAPSHOT installed.  That's the way it worked up until recently.

However, it also should be that if I check out 3.3.0-alpha5 and build it then that's what I should get unless I monkey with settings.

Whatever CI is doing should not affect the user experience.  CI can embed whatever it needs so we shouldn't require every potential contributor to have to monkey with settings to get things working 'normally'.

If we have to update our release processes to support this notion then so be it... but I think even that could be done automatically if comparing the latest tag commit ID to the current commit ID, etc..  I'm just not sure how much we want to go down that route given that 'version rolling' is usually a pretty simple and common part of a release process.

As it is now, it really sucks because if I just want to pull JME and test something I either have to figure out how to change what version is being built or modify every downstream project to use some weird vdfh24362hvjkhw4v6262462346bhkjhv string just to build.  (I just updated to test something and I already hate this with the fury of a thousand burning suns.)
