### ISSUE TITLE
MorphTrack.cloneFields() is incomplete

### ISSUE THREAD

**Issue by stephengold** [jMonkeyEngine/jmonkeyengine#1350]
Found by code inspection...

The `cloneFields()` method of `com.jme3.anim.MorphTrack` doesn't clone the weight array, the time array, nor the interpolator. As a result, the cloned `MorphTrack` shares all these objects with the original, leading to unexpected side-effects if one of them is later modified.

In order to fully resolve this issue, `FrameInterpolator` will need to be made `Cloneable` or `JmeCloneable`.

**Comment by pspeed42** [comment]
FrameInterpolator is a weird one.  This line:
https://github.com/jMonkeyEngine/jmonkeyengine/blob/f6525912817fed374ad0a68b831a25cea6487b81/jme3-core/src/main/java/com/jme3/anim/MorphTrack.java#L55

Makes it seem like they are supposed to be reused/shared across tracks and stuff.  But there certainly does seem to be a lot of 'state' on FrameInterpolator.

Regarding the arrays, I think they are similarly meant to be like mesh data: essentially shared across clones.  It looks like the only way that a user can manipulate these values is by calling the getter and the monkeying around with the returned array... but that idiom is bad news all over JME.

So I wonder if these are an actual issue in practice since these values are only used to calculate the final weights but they are all otherwise input to the calculations.

**Comment by Ali-RS** [comment]
Yes, just like the TransformTrack that should share Transforms and times across tracks 
https://github.com/jMonkeyEngine/jmonkeyengine/blob/607e068f761b3b181df912dd696f628f5d8458e4/jme3-core/src/main/java/com/jme3/anim/TransformTrack.java#L49

the weights and times arrays in MorphTrack are also supposed to be shared across tracks when cloned.

**Comment by pspeed42** [comment]
Maybe we should add some comments in the clone fields method to help future explorers avoid the same misunderstanding.

**Comment by Ali-RS** [comment]
Yeah, that would be good.

**Comment by stephengold** [comment]
I agree that the idiom of returning a reference to an internal object is "bad news". Nehon loved it, used it repeatedly, and never documented it when he did. In the case of `TransformTrack` and `MorphTrack`, we didn't bother to change them prior to 3.3, so now we're stuck.

I discovered this while I was working on Wes, my animation editing library.

To my mind, the semantics of cloning are clear. After cloning a mutable object, I expect to be able to modify it without affecting the original. I'm fine with time arrays being shared between tracks of a single `AnimClip`; that doesn't lead me to expect they'd also be shared between clones of a specific track.

**Comment by Ali-RS** [comment]
But note deep cloning TransformTrack and MorphTrack for each instance could result in HUGE memory usage.

I guess they would better be immutable instead, once created you should not be able to modify them. Or at least we can add some comments to avoid the misunderstanding as Paul said.

**Comment by pspeed42** [comment]
re: "I agree that the idiom of returning a reference to an internal object is "bad news"."

The "bad news" is users who expect to be able to do it.  Almost 100% of the time in JME if you call a getter and modify the value directly then you will have a bad time.  This is because JME has opted for speed over hand holding in most cases.  Rather than creating throw-away objects to project one or two users at the expense of time and garbage, it chooses to return objects directly.

Regarding the cloning, it's also quite common that JME does a deep clone only as deep as makes sense.  Actually, the real surprise with calling clone() is that it does a deep clone at all.  Most Java developers are taught to assume the clone() will return a shallow clone unless told specifically otherwise.

So, re: "After cloning a mutable object, I expect to be able to modify it without affecting the original."

In Java, after cloning a mutable object then you should expect to be able to mutate the object... but not the objects that it holds.  And that's true in these cases.

**Comment by stephengold** [comment]
I disagree, but I don't wish to argue about things that can't or won't be changed.

If this is purely a documentation issue, the next step is to decide what the documentation should say. How about something to the effect that:
 1. once passed to the track constructor (or `setKeyframes()` etcetera) arrays, vectors, and quaternions should not be modified, and that
 2. arrays, vectors, and quaternions returned by  `getWeight()` and `getTimes()` etcetera should be treated as read-only objects.

**Comment by Ali-RS** [comment]
>2. arrays, vectors, and quaternions returned by getWeights() and getTimes() etcetera should be treated as read-only objects.

Yes.

**Comment by stephengold** [comment]
I'll write up a fix and commit it, then.
