### ISSUE TITLE
detached node receives update

### ISSUE THREAD

**Issue by kkolyan** [jMonkeyEngine/jmonkeyengine#1363]
1. create node A
2. create node B and attach it to A
3. detach node B by code in `update` of A
* Expected: B's `update` never invoked anymore after its detached.
* Actual: B's `update` invoked once at the same frame when it was detached (despite of having `null` parent).

Reproduced in versions: 3.3.0-stable (used in my project), 3.1.0-alpha (the earliest in maven repo)

I caught it when migrated from **some old** version to 3.3.0-stable. I say "some old", because cannot detect exact version - I downloaded it from site many years ago. Files inside jar are dated by "2011-10-22 22:41".

The reason of bug is new mechanism of nodes iteration - JME has single `updateList` instead of node graph traversal each time. In my old version JME did traverse graph recursively and detached nodes never receives updates (at least if they were detached by any parent node control).

Reproduction code example:
[jme-detached-node-updated.zip](https://github.com/jMonkeyEngine/jmonkeyengine/files/4533841/jme-detached-node-updated.zip)
<details>
  <summary>Show code</summary>
  
~~~
package net.kkolyan.mm.misc;

import com.jme3.renderer.RenderManager;
import com.jme3.renderer.ViewPort;
import com.jme3.scene.Node;
import com.jme3.scene.Spatial;
import com.jme3.scene.control.AbstractControl;
import com.jme3.scene.control.Control;
import org.junit.Assert;
import org.junit.Test;

import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Queue;
import java.util.function.Consumer;

public class DetachedNodeUpdatedTest{
    @Test
    public void test1() {
        Node rootNode = new Node("Root");

        Node bossNode = new Node("Boss");
        rootNode.attachChild(bossNode);

        Node badEmployee = new Node("Bad Employee");
        bossNode.attachChild(badEmployee);

        Node goodEmployee = new Node("Good Employee");
        bossNode.attachChild(goodEmployee);

        final Queue<Spatial> fireList = new ArrayDeque<>();
        bossNode.addControl(new Boss(fireList));

        final List<String> reports = new ArrayList<>();
        goodEmployee.addControl(new Employee(reports::add));
        badEmployee.addControl(new Employee(reports::add));

        fireList.add(badEmployee);
        rootNode.updateLogicalState(1f);

        Assert.assertEquals(Arrays.asList("Good Employee"), reports);

    }

    private static class Boss extends AbstractControl {
        private final Queue<Spatial> fireList;

        public Boss(final Queue<Spatial> fireList) {
            this.fireList = fireList;
        }

        @Override
        protected void controlUpdate(final float tpf) {
            while (true) {
                Spatial toFire = fireList.poll();
                if (toFire == null) {
                    break;
                }
                ((Node)getSpatial()).detachChild(toFire);
            }
        }

        @Override
        protected void controlRender(final RenderManager rm, final ViewPort vp) {
        }

        @Override
        public Control cloneForSpatial(final Spatial spatial) {
            throw new UnsupportedOperationException();
        }
    }

    private static class Employee extends AbstractControl {
        private final Consumer<String> reportConsumer;

        private Employee(final Consumer<String> reportConsumer) {
            this.reportConsumer = reportConsumer;
        }

        @Override
        protected void controlUpdate(final float tpf) {
            reportConsumer.accept(getSpatial().getName());
        }

        @Override
        protected void controlRender(final RenderManager rm, final ViewPort vp) {
        }

        @Override
        public Control cloneForSpatial(final Spatial spatial) {
            throw new UnsupportedOperationException();
        }
    }
}

~~~
</details>

**Comment by stephengold** [comment]
Thanks for the bug report.

I'm unsure which behavior is more correct, the old or the new. I'll leave that for someone else to decide.

**Comment by pspeed42** [comment]
The old code tried to modify the list while it was being iterated which would cause random behavior.  For example, if child 1 was removed while we were on child 2 then things got weird.

Now things are 100% predictable, when update() is called, all current children will get update() called.

Bottom line: if you extend Spatial (bad practice number 1) and remove children from the parent during update (bad practice number 2) then you will have to carefully manage your own update loop for the children to work around the issues you created for yourself.

Note: those issues were there before but they would come up at random times instead of consistently.

You may also want to revisit your design to avoid bad practices.

**Comment by kkolyan** [comment]
> if you extend Spatial (bad practice number 1)

Yeah, I do not extend Spatial :) Sorry for ambiguity, I used `node A does something` as shortcut for `Control on node A does something`


> and remove children from the parent during update (bad practice number 2)

I'm not sure I understand you. Node B is child of node A. Control `Boss` is added to node A. Is it bad to detach B from `controlUpdate` method of Boss?


Hm. I got you. Interesting. need to think how it would be better. For me constraint "Parent update is before child update" is a bit obvious. And fact that it's not good if siblings delete each other - intuitive too. 

> if child 1 was removed while we were on child 2 then things got weird.

I'm not 100% sure, but as I know, in old behavior sibling detach from another sibling will not prevent update, because direct children list is determined right after exit of parent `control update` and ignores changes during iteration. Such behavior looks intuitive.

**Comment by pspeed42** [comment]
Old behavior was to iterate by index and hope for the best.  Then when there were problems with children getting removed, they decided to iterate backwards and hope for the best.

Now, when the parent update happens, it grabs a snapshot of the child list so that it won't move around while iteration is happening.  When parent.update() is called, every child that existed at that time is guaranteed to get an update() call... regardless of whether or not they've removed themselves, added someone else, which added themselves back again, etc..  The child list can change 500 times during that iteration and it will not change who gets an update().

Moreover, some children might want that.  Just because they aren't connected to a parent anymore doesn't mean that they don't want that last update.

re: "I'm not sure I understand you. Node B is child of node A. Control Boss is added to node A. Is it bad to detach B by code inside controlUpdate method of Boss?"

It's probably fine... most times it's fine... but then what is node B doing that cares about parentage?  Perhaps it's the control on B that's actually broken.

**Comment by kkolyan** [comment]
> Old behavior was to iterate by index

Hm, my bad. then it's really may be unpreditable.

> Now, when the parent update happens, it grabs a snapshot of the child list so that it won't move around while iteration is happening. When parent.update() is called, every child that existed at that time is guaranteed to get an update() call... regardless of whether or not they've removed themselves, added someone else, which added themselves back again, etc.. The child list can change 500 times during that iteration and it will not change who gets an update().

Saying `parent` you mean `root` and saying `child` you mean `descendant`, right? In my "model of dream" it works the same, but applicable to each node with its direct breed, instead of root and one global list of children.

> Moreover, some children might want that. Just because they aren't connected to a parent anymore doesn't mean that they don't want that last update.

It's a point, but if we treat it as a feature, we should guarantee last call (it's not so, as I understand)

**Comment by pspeed42** [comment]
We modified the code to roll up the "active" nodes to the root so that we didn't have to traverse the whole scene graph just to update a handful of controls.  In the end, it makes a pretty big different, especially when there are few or no controls (like in an ES based game).  The old way, if you had a 3000 node tree of some complexity then JME would traverse all 3000 of them every frame just in case they had a control on them.

**Comment by kkolyan** [comment]
ok, thanks for explanation! What does mean `ES based`?

**Comment by pspeed42** [comment]
"ES based" = "entity system based".  Like, entity-component-system.  Most of the time in an ES based game, it's the case where an app state manages some set of spatials rather than having a control per spatial.

**Comment by kkolyan** [comment]
Interesting. Could you suggest me any open-source games where this pattern used at full power to get more aquainted with this approach?

**Comment by pspeed42** [comment]
As a matter of fact, I wrote an open source library could Zay-es which is the framework for entity-system based games in JME: https://github.com/jMonkeyEngine-Contributions/zay-es
...it has a couple of examples.
There is also this more complicate SimEthereal + Zay-ES real-time networking example:
https://github.com/Simsilica/Examples/tree/master/sim-eth-es

**Comment by kkolyan** [comment]
Thank you!

**Comment by kkolyan** [comment]
It's very interesting. Looks like it's the opposite of enterprise-like design I use now :)  Will try it in future projects.

**Comment by stephengold** [comment]
I'm closing this issue. Feel free to continue your conversation here or move it to the [JMonkeyEngine Forum](https://hub.jmonkeyengine.org/) if that suits you.
