### ISSUE TITLE
LODGeomap creates index buffers with elements too small 

### ISSUE THREAD

**Issue by stephengold** [jMonkeyEngine/jmonkeyengine#1382]
In the jme3-terrain library, the `LODGeomap` class allocates index buffers for each `TerrainPatch` using `IndexBuffer.createIndexBuffer()`. It does so assuming that the number of vertices in the mesh is less than or equal to the number of indices, but this erroneous.

Consider the `TerrainTest` application in jme3-examples. With the current lod multiplier of 2.7 (specified in the `DistanceLodCalculator` constructor) only 3 LODs are actually used. If we change the multiplier to a lower value, such as 1.0, then all 6 LODs will be used, and some of the more distant terrain patches disappear entirely. If we lower it further, to 0.5, then large swaths of terrain vanish.

`LODGeomap` is allocating `ByteBuffer`s for indices, then trying to write indices greater than 255 to them. I added range checking to `IndexByteBuffer.put(int i, int value)` and saw values such as 2112 being passed down from `LODGeomap.writeIndexArrayLodDiff()`. If I replace the `createIndexBuffer(numIndexes, numIndexes)` calls in `LODGeomap` with `createIndexBuffer(66666, numIndexes)`, `IntBuffer`s are allocated, and the missing terrain patches re-appear.

1. It's very bad that `IndexByteBuffer` and `ShortByteBuffer` don't do any range checking on their inputs.
2. `LODGeomap` needs to correctly calculate the number of vertices, or else it should always use `IntBuffer`s.

**Comment by pspeed42** [comment]
They shouldn't have to do range checking because the underlying jni buffers should be.  It's a bit surprising that ByteBuffer.put() is allowing out of range values.  It should be throwing IndexOutOfBoundsException.

**Comment by pspeed42** [comment]
re: " It does so assuming that the number of vertices in the mesh is less than or equal to the number of indices, but this erroneous."
I'm not sure I see that code.  The index buffer size seems to be created based on the LOD level, etc. in private int calculateNumIndexesLodDiff(int lod)

When calling createIndeBuffer() normally the vertex count and index count are passed separately and LODGeomap is indeed incorrectly passing index count for both... but that's the right value for the size of the buffer.  The reason they are normally both passed is so that the method can decide which type of buffer to use.  If you only have 255 vertexes then it can use a ByteBuffer for the values.  If you have 100,000 vertexes then it must use and int buffer.

Oh, wait... are you saying that the issue is that it is selecting the wrong buffer type?  I guess if you only want 255 indexes but there are a million vertexes then it will return a bad value.  That's also a super easy fix.  Pass the right value as the first argument to createIndex().  (width * height * 3 or position buffer limit())

And if that's really what's going on then this isn't really a 'range check' issue in the usual sense as there are plenty enough values in the buffer.  They just don't have the resolution to hold what's being asked.  Ok, I guess that is a 'range check' of sorts... but it's checking the value and not the index.  May not be obvious to the reader.  I also don't think we should do it.  We've adopted the semantics of the underlying nio buffers which also don't range check our values for us.

**Comment by stephengold** [comment]
Re: range checking. If we're confident that `LODGeomap` is the only place where a too-small numVertices is passed to `createIndexBuffer()` then we don't need to range-check the `put()` values.

Back when the only `IndexBuffer` types were `int` and `short`, you could punt the calculation of numVertices because it rarely mattered. Few meshes have indices that overflow a `short`. But now we've got a situation where a recent enhancement (to allow `ByteBuffer` for indices) is uncovering 8 year-old bugs in legacy code. (For another example, see issue #1197.) It seems risky to assume this bug is the last of its kind.

If this were my project, I'd probably have included a range check when `IndexByteBuffer` was written. And if I'd neglected to, I'd definitely add one now that I've been bit by this issue. Can't we at least add an `assert`?

**Comment by pspeed42** [comment]
Sure.  Add an assert.  That way we don't slow down all code for that 0.000001% of cases where a developer does something dumb and then never tests it.

**Comment by pspeed42** [comment]
It's really too bad we can't detect this case in the create method because 99% of the time if the vertex count and index count matches then something is wrong.  It's that 1% of times where some combination of LODs might coincidentally match that makes it hard.

**Comment by stephengold** [comment]
How about recording numVertices in the IndexBuffer when it is instantiated, so the assert can test against that limit instead of 255?

**Comment by stephengold** [comment]
Solved by PR #1418 in master branch at 507cc221

**Comment by stephengold** [comment]
Verified the fix in v3.4.0-beta4.
