### ISSUE TITLE
TerrainQuad meshes include extraneous triangles

### ISSUE THREAD

**Issue by stephengold** [jMonkeyEngine/jmonkeyengine#1390]
There appears to be a bug in mesh generation for terrain quads when the patch size is 9 or greater. To see this, generate a 9x9 quad with random heights and apply a wireframe material.
![screenshot1](https://user-images.githubusercontent.com/2287609/90800237-40b30780-e2c9-11ea-93af-9823620a91fc.png)

**Comment by pspeed42** [comment]
Are the triangles visible in the actual mesh?

I think it's a triangle strip so it's going to have 'lines' of degenerate triangles to reset the 'pen' every so often.  Just wondering if that's what we're seeing here.

**Comment by stephengold** [comment]
The image above is an actual mesh. So yes, they're visible.

For typical terrain, the extra triangles would be nearly coplanar with the surface, so they'd be difficult to see.

**Comment by stephengold** [comment]
I don't understand what's going on here. I specified a terrain size of 9 and a patch size of 9, but 4 patch geometries were generated, each containing 25 vertices.

**Comment by pspeed42** [comment]
You will see degenerate triangles (triangles that are colinear) in a wire frame view but you wouldn't in an actual non-wire view no matter which angle you viewed them out.  Like in this case:
![image](https://user-images.githubusercontent.com/7004062/90804190-deb5ca80-e2e7-11ea-92ef-30ab72bf4367.png)
That's either an invisible wire above/below the surface (hard to tell above or below here) or a small triangle wall above/below the surface.  The first is potentially expected behavior.  The latter is clearly a bug.

But when making a triangle strip, it's common to repeat a vertex to create a degenerate triangle to get the proper winding order for the next triangle.  Usually at the end of each row.  This is because the winding order alternates between each vertex to support the zigzagging of triangles.  Given the other strangeness in how JME terrain generates border meshes and so on, I can't promise that the above picture is nonsense... and given that there appears to be a similar line at two of the other corners it's even harder to say.  Still weird, though.

**Comment by pspeed42** [comment]
JME terrain is unfortunately a bit of a mess.

**Comment by stephengold** [comment]
Thanks for the clarification. I agree about the mess. I discovered this while trying to make the physics mesh diagonals match the TerrainQuad mesh diagonals. Even with LOD disabled, that's looking increasingly difficult.

If I decide to investigate further, how would you suggest I proceed to determine whether there's a bug or not? Dump the index and position buffers to a file?

**Comment by pspeed42** [comment]
If it were me... I'd use that example you already have and render the wireframe on top of the non-wire frame and see if those stringers are triangles or just wires.

**Comment by stephengold** [comment]
I followed your advice and convinced myself that, in the 9x9 TerrainQuad at least, all the extra triangles are degenerate. Closing this issue.
