### ISSUE TITLE
Mouse Coords in LWJGL3 are being multipled by scaling factor on all machines causing coords to be off.

### ISSUE THREAD

**Issue by bob0bob** [jMonkeyEngine/jmonkeyengine#1745]
if you create a window of 100x100 and have a display that reports DPI scaling.  GlfwMouseInput.     private void onCursorPos(final long window, final double xpos, final double ypos) 

this method is multiplying the mouse coord by the monitor scaling even when not being used.  It causes anything based on mouse coords to fail.   Specially GUI, mouse clicks on buttons and such are off by 2.5 times.

**Comment by stephengold** [comment]
Thanks for opening this issue. Please re-test with v3.5.0-beta7.

**Comment by stephengold** [comment]
Default setting for "UseRetinaFrameBuffer" changed from `true` to `false` in "v3.5" branch at c44d74b4 and in "master" branch at a1ae3fd.

**Comment by stephengold** [comment]
I'm working on a PR coming with further changes.

**Comment by bob0bob** [comment]
Retina setting doesn't affect the scaling.  It was added as a "MUST" and not a "IF".

**Comment by stephengold** [comment]
> Retina setting doesn't affect the scaling. It was added as a "MUST" and not a "IF".

I addressed that in PR #1746.

**Comment by riccardobl** [comment]
In mac os HiDPI makes the framebuffer "physically" bigger, making it 2x or 3x the size in pixels of the window, that's the reason for the scaling, but it seems in other systems the hidpi fb is handled transparently and it is made to look as if it had the same number of pixels to the gl api(?).

I think the solution to this issue is to calculate the scaling manually with  glfwGetFramebufferSize/glfwGetWindowSize
