### ISSUE TITLE
Skinning.glsllib fails compilation when NUM_WEIGHTS_PER_VERT = 1

### ISSUE THREAD

**Issue by zzuegg** [jMonkeyEngine/jmonkeyengine#1879]
Line 53:
`tangent = m_BoneMatrices[int(inHWBoneIndex.x)] * tangent;`
is 
`vec3 = mat4*vec3`

I  will fix it when someone more capable at math says how. i guess:
``tangent = (m_BoneMatrices[int(inHWBoneIndex.x)] * vec4(tangent,1.0f)).xyz;``

should work?

**Comment by stephengold** [comment]
I'm not very knowledgeable regarding GLSL.

One thing I don't understand: 
+ Line 7 has `#define NUM_WEIGHTS_PER_VERT 4` so how could `NUM_WEIGHTS_PER_VERT` ever be 1?

Mathematically, I don't think `tangent = (m_BoneMatrices[int(inHWBoneIndex.x)] * vec4(tangent,1.0f)).xyz;` is correct, since `m_BoneMatrices[int(inHWBoneIndex.x)]` probably includes a translation component, which shouldn't be applied to direction vectors such as normals and tangents.

In light of line 66, I would expect rotation of tangents to be analogous with the rotation of normals. Something like:
```glsl
        tangent = (mat3(m_BoneMatrices[int(inHWBoneIndex.x)][0].xyz,
                        m_BoneMatrices[int(inHWBoneIndex.x)][1].xyz,
                        m_BoneMatrices[int(inHWBoneIndex.x)][2].xyz) * tangent);
```
should work.

Or, if we're concerned with readability, compute a `rotMat` that can be applied to both normals and tangents:
```glsl
        mat3 rotMat = mat3(m_BoneMatrices[int(inHWBoneIndex.x)][0].xyz,
                           m_BoneMatrices[int(inHWBoneIndex.x)][1].xyz,
                           m_BoneMatrices[int(inHWBoneIndex.x)][2].xyz);
        tangent = rotMat * tangent;
        normal = rotMat * normal;
```
