### ISSUE TITLE
 jme3-plugins imports NegativeScaleTest incorrectly

### ISSUE THREAD

**Issue by stephengold** [jMonkeyEngine/jmonkeyengine#2087]
I noticed a defect in GltfLoader while developing the MonkeyWrench library.

The test data is [NegativeScaleTest from Khronos's glTF sample models](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/NegativeScaleTest).

Here's how it looks in CompareLoaders when "NegativeScaleTest/glTF/NegativeScaleTest.gltf" is loaded using jme3-plugins:

![NegativeScale](https://github.com/jMonkeyEngine/jmonkeyengine/assets/2287609/167e4fc1-51f3-41af-bc2b-60d91de47f63)

According to the documentation for NegativeScaleTest, this indicates "back-face culling being inappropriately applied to negatively-scaled meshes" plus normal vectors not flipped.

I haven't investigated to see how difficult the solution might be.

**Comment by pspeed42** [comment]
As mentioned elsewhere, because JME composes scale in parallel to translation and rotation, there are 90% of very logical things with weird scaling that will just never work right.
For example:
Node(scale(-1, 1, 1))
-> Node(translation(10, 0, 0))
    -> Node(scale(-1, 1, 1))
        -> Geometry(translation(10, 0, 0))
Logically, the geometry should be at 0, 0, 0.... I suspect JME will put it at 20, 0, 0.

**Comment by stephengold** [comment]
Using "master" branch at Git hash 5975b3f7, I verified that NegativeScaleTest now renders correctly.
