### ISSUE TITLE
PBRLighting incompatible with Glow.frag

### ISSUE THREAD

**Issue by codex128** [jMonkeyEngine/jmonkeyengine#2161]
Since PBRLighting does not contain GlowMap or GlowColor material parameters, it is incompatible with Glow.frag. As a result, glow does not work with PBRLighting.

See also: https://github.com/jMonkeyEngine/jmonkeyengine/pull/2088#issuecomment-1753329540

**Comment by stephengold** [comment]
What's the advantage of using GlowMap or GlowColor instead of EmissiveMap and Emissive?

**Comment by pspeed42** [comment]
GlowMap and GlowColor are what Lighting.j3md uses.  EmissiveMap and Emissive are what PBR uses.
...but PBR is using the glow technique stuff from Lighting.j3md and so essentially doesn't work for 'object' level glow.  So I believe the suggestion (and the code bears this out) is to make PBR compatible with glow by using EmissiveMap and Emissive instead of GlowMap and GlowColor.

**Comment by codex128** [comment]
@pspeed42 is correct. Glow.frag requires GlowMap and GlowColor material parameters, which PBRLighting does not have; it has EmissiveMap and Emissive material parameters instead.

**Comment by stephengold** [comment]
Should similar changes be made to PBRTerrain.j3md and AdvancedPBRTerrain.j3md?

**Comment by codex128** [comment]
Neither matdef has a Glow technique, so at the moment, no.
