### ISSUE TITLE
 JMonkey Engine Theme Handling: Incorrect usage of Theme FG Color with non-theme background color

### ISSUE THREAD

**Issue by gbutler69** [jMonkeyEngine/jmonkeyengine#396]
Using "DarkMonkey" theme seems to make the start-up dialog for JMonkey Engine display incorrectly white text on a white background as shown in this forum post: http://hub.jmonkeyengine.org/t/jmonkey-engine-theme-handling-incorrect-usage-of-theme-fg-color-with-non-theme-background-color/34736

(see attachment as well)

![07c826072f777ab0e0fa8eee132eb0488d4cd6b3_1_397x500](https://cloud.githubusercontent.com/assets/1789892/12065332/68ff1b9c-afa3-11e5-8cef-c3fe2df23e34.png)

**Comment by Relic724** [comment]
I didn't do It! I swear! LOL.

I was burling through my e-mail and saw this. I made Darkmonkey with skinning Netbeans in mind, and I will say there is still some coding to be done. It could be made to work with the opening screen for a JME game, as well, I suppose.  

A lot of problems come up with Dark Themes, because the Foreground color becomes White(ish) and the Background becomes Black(ish).  It looks to be the case, here. It does not look like the background of the jPanel is drawing it's color from the Background as supplied by the FAC/LAF plugin. Is it taking it's color from somewhere else?

Regards,
Charles

**Comment by Relic724** [comment]
https://github.com/jMonkeyEngine/jmonkeyengine/blob/2ca55c8b3a37ec806e4512d8aecf43dbb156ccd2/jme3-desktop/src/main/java/com/jme3/app/SettingsDialog.java

ah... this might be it?

Line 291+
        /**
        * <code>init</code> creates the components to use the dialog.
        */
       private void createUI() {
           GridBagConstraints gbc;
        
           JPanel mainPanel = new JPanel(new GridBagLayout());
        
            try {
                UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            } catch (Exception e) {
                logger.warning("Could not set native look and feel.");
            }

        addWindowListener(new WindowAdapter() {

            @Override
            public void windowClosing(WindowEvent e) {
                setUserSelection(CANCEL_SELECTION);
                dispose();
            }
        });

So, I don't have DarkMonkey attributed with the System/Native boolean enabled... Is it being overwritten by the true Local/Native LAF?

**Comment by gbutler69** [comment]
Hey, thanks for the response. It turns out that I completely mischaracterized the issue. The problem has nothing to do with the Dark Monkey theme. The problem was entire an issue of the completely broken Ubuntu 15.10 Gnome/Gtk themes. As you showed in the Start-Up Dialog code, it is hard-coded to use the "Platform Look-and-Feel", which, in  my case would be Gtk and whatever theme is selected in Gtk. The problem was completely broken Gtk Theming.
