### ISSUE TITLE
64 bit JME3 installer crashes/fails on windows 10

### ISSUE THREAD

**Issue by Triangle345** [jMonkeyEngine/jmonkeyengine#405]
After clicking "next" on the first dialog, the installer goes away without error messages or any notification. However, the 32 bit installer seems to be working great.  This was on 64 bit windows 10

**Comment by MeFisto94** [comment]
Hey @Triangle345 
Can you retry with the latest release? See [here](https://github.com/jMonkeyEngine/sdk/releases/)

In case it doesn't work, see [here](https://github.com/jMonkeyEngine/sdk/blob/master/docs/reporting_issues.md#reporting-faults-in-the-netbeans-installer) on how to enable logging.

Just attach that log then (but please to the sdk repo now, because we've splitted them apart).
I only have W7 to test the installer on but we made some changes (using the latest jdk8 now)

**Comment by Triangle345** [comment]
The installer seems to be working now on Windows 10.  I'm not experiencing the issue described anymore. After uninstalling via "Add Remove Programs" in the Control Panel. I was able to install the 64 bit JME 3.1 A3 with no issue.

**Comment by MeFisto94** [comment]
But you had it before uninstalling JME3?

**Comment by Triangle345** [comment]
So I had the issue with the 64 bit installer I downloaded on Feb 5, 2015..But something on my machine seems to have resolved that issue as well. Overall, I'm not sure what caused it; as at this point this seems to be a non issue.  I need to investigate what state my Windows 10 machine was at the time of the failure.

**Comment by Triangle345** [comment]
Let me try a few things to reproduce the problem, i'l let you know this evening

**Comment by Triangle345** [comment]
Give me a day or two on this... still trying to recreate the issue.

**Comment by Triangle345** [comment]
I am unable to reproduce this. Windows 10 must of been in some odd state at the time of installation.

**Comment by MeFisto94** [comment]
Well, it seems that having an already installed version of jme on the system causes the installer to go in the unimplemented (?) "re-install" mode. 

Anyway I'm glad that it works in the meantime. If you experience any issues feel free to create an issue in the [sdk](https://github.com/jMonkeyEngine/sdk) repo
