### ISSUE TITLE
GL_CLAMP_TO_BORDER is not supported

### ISSUE THREAD

**Issue by Batzer** [jMonkeyEngine/jmonkeyengine#518]
The four texture addressing modes of OpenGL 3.3+ are _GL_REPEAT_, _GL_MIRRORED_REPEAT_, _GL_CLAMP_TO_EDGE_ and _**GL_CLAMP_TO_BORDER**_. The latter is not supported by JME3.1, but is needed to fully load a COLLADA model for example. All wrap modes should be available.

**Comment by shadowislord** [comment]
That mode is only useful if texture border is used, otherwise, the `GL_CLAMP_TO_BORDER` mode is equivalent to `GL_CLAMP_TO_EDGE`. Supporting `GL_CLAMP_TO_BORDER` only makes sense if jME3 supported texture border. You can safely translate `GL_CLAMP_TO_BORDER` into `GL_CLAMP_TO_EDGE` with no adverse effects.

**Comment by Batzer** [comment]
You are right, it does not make sense if no border color is specified. Thats exactly what we need for our project then, we need to fill the space beyond `[0,1]` with transparency. And sadly there is no straightforward way to adjust the texture coordinates to overcome this requirement. Is there a specific reason why texture border is not supported by jME3?

**Comment by shadowislord** [comment]
Can't you simply create the border manually in an image editor? Another option is to edit the image after loading it in jME3 to add the border.
Main reason why it is not supported is because OpenGL ES does not support texture border.

**Comment by shadowislord** [comment]
Going to close this since there's been no response
