### ISSUE TITLE
jME3 bullet native: CharacterController get blocked by GhostControl

### ISSUE THREAD

**Issue by ghost** [jMonkeyEngine/jmonkeyengine#57]
Reference on googlecode: https://code.google.com/p/jmonkeyengine/issues/detail?id=458

**Comment by stephengold** [comment]
I tried to reproduce this issue in current `master` branch (v3.3-6666 to be precise) by adding a `PhysicsGhostObject` to the `TestWalkingChar` test. The `CharacterControl` passed through the ghost object without impediment.  I therefore believe this issue was fixed at some point, probably on the Bullet end.
