### ISSUE TITLE
Cylinder.java: Wrong size of buffers for cylinders

### ISSUE THREAD

**Issue by TehLeo** [jMonkeyEngine/jmonkeyengine#640]
```
Cylinder r = new Cylinder(3, 3, 1, 1, true);
IndexBuffer ib = r.getIndexBuffer();
System.out.println("ib " + ib.size() + ", v: " + r.getVertexCount());
```
Outputs "ib 90, v: 22". That means 30 triangles.
Expected value: 12 triangles for cylinder + tris for caps, (if not dealing with special case) 3 triangles per cap = 18 triangles and 17 vertices
(if dealing with special case) 14 triangles and 15 vertices
```
Cylinder r = new Cylinder(3, 3, 1, 1, false);
IndexBuffer ib = r.getIndexBuffer();
System.out.println("ib " + ib.size() + ", v: " + r.getVertexCount());
```
Outputs "ib 36, v: 12".  That is 12 Triangles.
Expected value: 12 Triangles and 9 vertices.

**Comment by shamanDevel** [comment]
Hi,
I think the output is as expected. Let's look at your second example first:
You set radialSamples = 3, so you get a prism (3 radial vertices). Furthermore, axisSamples = 3, leading to three segments along the axis. This means 4 vertices along the axis (axisSamples=1 -> top, bottom; axisSamples=2 -> top, middle, bottom; axisSamples=3 -> top, 2x middle, bottom). This leads to 3*4=12. So the vertex count is correct.
The index buffer is also correct because it stores three integers per triangle. So the actual number of triangles is ib.size()/3 = 36/3 = 12 which is the correct value.
The same holds for your first example.

**Comment by Saucistophe** [comment]
Rays seems to think otherwise:

java.lang.IndexOutOfBoundsException
	at java.nio.Buffer.checkIndex(Buffer.java:540)
	at java.nio.DirectFloatBufferU.get(DirectFloatBufferU.java:253)
	at com.jme3.collision.bih.BIHTree.initTriList(BIHTree.java:92)
	at com.jme3.collision.bih.BIHTree.<init>(BIHTree.java:135)
	at com.jme3.collision.bih.BIHTree.<init>(BIHTree.java:139)
	at com.jme3.scene.Mesh.createCollisionData(Mesh.java:965)
	at com.jme3.scene.Mesh.collideWith(Mesh.java:994)
	at com.jme3.scene.Geometry.collideWith(Geometry.java:457)
	at com.jme3.scene.Node.collideWith(Node.java:611)
	at com.jme3.scene.Node.collideWith(Node.java:611)

It took me forever to debug it, but I found that changing the number of radial samples makes it work.
with 8 samples, ray collision fail about 3 times out of 4; with 9, it works every time.

I'll try to create a SSCCE.

**Comment by Saucistophe** [comment]
There you are.
```java
Random random = new Random();
int ok = 0;
int ko = 0;

@Override
public void simpleUpdate(float tpf)
{
	rootNode.detachAllChildren();

	Cylinder cylinder = new Cylinder(2, 8, 1, 1, true);
	Geometry geometry = new Geometry("cylinder", cylinder);
	geometry.rotate(FastMath.HALF_PI, 0, 0);

	Material mat = new Material(assetManager, "Common/MatDefs/Misc/Unshaded.j3md");
	mat.getAdditionalRenderState().setWireframe(true);
	geometry.setMaterial(mat);

	rootNode.attachChild(geometry);

	Ray ray = new Ray(new Vector3f(random.nextFloat(), random.nextFloat(), random.nextFloat()), new Vector3f(random.nextFloat(), random.nextFloat(), random.nextFloat()));
	CollisionResults collisionResults = new CollisionResults();

	try
	{
		rootNode.collideWith(ray, collisionResults);
		ok++;
	}
	catch (java.lang.IndexOutOfBoundsException ex)
	{
		ko++;
	}
	if ((ko + ok) % 100 == 0)
		System.out.println("Ok : " + ok + ", Ko : " + ko);
}
```

It's strange that it's occuring randomly, but I get :
Ok : 13948, Ko : 1552
Which is roughly 1 cylinder out of ten that's off.

I stopped the simulation once an incorrect cylinder is generated, and here it is:
![image](https://user-images.githubusercontent.com/7082839/27159741-b1d3c36c-516f-11e7-8fba-6a940ff61708.png)

Results seem to vary, strangely:
![image](https://user-images.githubusercontent.com/7082839/27159752-ced3e46a-516f-11e7-9899-5660ccb63a18.png)

Hope this helps.

**Comment by Saucistophe** [comment]
I'm looking into it; I'll try to document the class better.
First of all, the javadoc is not clear about what "axis samples" means.
@shamanDevel thought it means the number of segments, I think it's the number or vertices per vertical edge (the number of segments +1). Here is a 3x3 cylinder rendered:
![image](https://user-images.githubusercontent.com/7082839/27203117-a18acbda-5224-11e7-9cd3-da1fb8406acd.png)

**Comment by shamanDevel** [comment]
@Saucistophe a question to your code above:
You indicate that the cylinders itself change. How can that happen? There is no randomness involved in the creation of Cylinder.

**Comment by Saucistophe** [comment]
@shamanDevel That is indeed the question.
I came here because my application crashes randomly, and I tracked it down to the cylinder.
If you run a simple application with the simpleUpdate above, you'll see the cylinder will render correctly, but one frame out of ten, you'll get an extra triangle or a nasty triangle glitch.

I've refactored the cylinder generation code into something more readable, but I still get the glitch.
I'll push the code by Sunday, I hope I'll find what's wrong by then.
