### ISSUE TITLE
[Feature request] JavaFx Support for jMonkeyEngine

### ISSUE THREAD

**Issue by john01dav** [jMonkeyEngine/jmonkeyengine#666]
jMonkeyEngine already has support to render to a swing window via the JmeCanvasContext. It, however, has no such support for JavaFx. I would like to request that this support be added.

This feature would allow for tools to be made that work with JME using a modern GUI framework, thus improving the quality of JME significantly. 

There are several ways I can see this being done from a technical standpoint:
 - Render to a borderless Swing or LWJGL window and move that window around to match a javafx component while always on top. I tried implementing this, and it works but is also _very_ buggy.
 - (https://github.com/empirephoenix/JME3-JFX)[This]. I tried to get this api working, but the documention is incredibly poor and the project also appears inactive.
 - (https://github.com/SgtRumbi/LWJGLJavaFX)[This]. Since this seems to allow the opengl rendering from JME to be inserted directly into JavaFx's rendering, I think this is the best option. It avoids the buggyness of a swing window overlay, and should be more efficient that JME3-JFX's method of shuffling images around.

**Comment by empirephoenix** [comment]
Since i stopped using the first one, I also stopped doing work for it. It should however still work. The part leading me to abaddon it is however still present (also with the other solution) 
-> JavaFx makes way to heavy use of reflection, making it feel somewwhat sluggish
-> There appears to be no real development effort anymore to actually improve it from Oracle side, there are currently some very annoying bugs open since Java7, and not even assigned to someone in the bugtracker.
-> The runtime support for other than oracle jvm is decaying, for example it is next to impossible to cleanly create a project that runs on both openjdk and oracle jdk with the same sources.

**Comment by john01dav** [comment]
Those are some really good points, some of which I wasn't aware of. In light of that, however, what GUI api do you recommend for nice looking (read: not swing or native) Java applications?

**Comment by Nehon** [comment]
Swing works fine IMO. Has it querks sure... But it's solid. Look for substance LAF. They have a couple of nice skins.

**Comment by atomixnmc** [comment]
@empirephoenix This kind of insights on JavaFx make any Java developers tatse feel of the fear... of getting old and get abandoned again. I don't have such kind of problems with JavaFx since I didn't use it with OpenJDK. Anyway, Oracle make everything look bad, the community still there and growing. I still think is a good point if efforts spend to make JME3 work in JavaFx the way it worked in swing

**Comment by Nehon** [comment]
Well, @empirephoenix was just reporting of his own experience, which I trust pretty thorough about javafx and JME. He was not prophesying the end of java.

**Comment by grizeldi** [comment]
Fixing missing java fx in openjdk on linux is actually just one terminal line:
sudo apt-get install openjfx
And it works just fine.

**Comment by JavaSaBr** [comment]
@john01dav https://github.com/JavaSaBr/JME3-JFX
