### ISSUE TITLE
Android support doesn't work

### ISSUE THREAD

**Issue by SpaceboyRoss01** [jMonkeyEngine/jmonkeyengine#692]
The jMonkeyEngine is showing this in the log:
```
*************************************************************************
The "android" command is deprecated.
For manual SDK, AVD, and project management, please use Android Studio.
For command-line tools, use tools/bin/sdkmanager and tools/bin/avdmanager
*************************************************************************
Invalid or unsupported command "update project --target --name Explorations --path /home/spaceboyross/Explorations/mobile"
Supported commands are:
android list target
android list avd
android list device
android create avd
android move avd
android delete avd
android list sdk
android update sdk
```
I have the latest jMonkeyEngine, and the latest Android SDK.

**Comment by shadowislord** [comment]
@MeFisto94 should this issue should go under the SDK?

**Comment by MeFisto94** [comment]
Yes it definitely should, however I am closing this for now.

A workaround is to use a older android sdk version or (what seems recommended) to just import the project into Android Studio (which you might need anyway, to design your activities and such), and make the Android SDK download there.

So you won't run the android game directly from the SDK but the Android Studio then. This is because Netbeans' Android Support Plugin is buggy currently and the new command line has become so complicated that you end up in parsing hell (the old version had java methods which could simply be called)
