### ISSUE TITLE
request: implement lz4 compression

### ISSUE THREAD

**Issue by rjbergTU** [jMonkeyEngine/jmonkeyengine#851]
Hello,

I saw in the javadoc that you have support for zip and gzip compression for networking. I think that the lz4 algorithm would be good to have also. This because compression, and especially decompression are faster with this algorithm. (Although the compression ratio is lower)

As this project is aimed at gaming, I think it would be good to offer the option, to reduce latency. 

I would not give it very high priority though. Having network compression is not a core feature of a game engine. I also have no personal interest (yet).

**Comment by pspeed42** [comment]
I'm not even sure that the existing zip messages even work... but it's super easy for users to just write their own messages based on them if they do.  This is not an engine feature, in my opinion.  Also, 9 times out of 10, the zipping takes as long as the 'latency' you save in the networking.

**Comment by rjbergTU** [comment]
Why not remove or deprecate the feature then?

Also, I wish I knew this before I suggested disk caching for networking. Sorry to bother you with that.

**Comment by pspeed42** [comment]
re: "Why not remove or deprecate the feature then?"
Because it might be working.  Some users might be using it.  I don't know.  I would never use it and I'm the one who rewrote SpiderMonkey.  

As to the other:
Before you waste a lot of the core dev's time putting in issues in the tracker, you could post messages to the forum about your ideas and get feedback there from a much larger audience.
