### ISSUE TITLE
request: implement to disk serializing for (compressed) messages

### ISSUE THREAD

**Issue by rjbergTU** [jMonkeyEngine/jmonkeyengine#852]
Hello, 

I think it would be nice for the network engine to be able to "cache" messages on-disk. This would allow ahead of time compression for compressed messages. This could be used to possibly reduce loading times in some games.

Possible use cases I can think of:

Loading games over network

**Comment by pspeed42** [comment]
Loading games over a network should be done with a protocol meant to handle moving large amounts of data quickly... like HTTP.

SpiderMonkey is meant for real time messaging for games.  All of the messages are potentially generated PER CLIENT.  There is no way to really support this feature without a lot of ugly code and in the end no one would use it because it's the worst way to do the provided use-case.

For a better approach to "loading games over network", see "getdown": https://github.com/threerings/getdown

**Comment by rjbergTU** [comment]
All right, sorry to bother you then. Just thought it could be useful for games with a lot of huge data files. But you are right, that could be done seperately without changing anything.

**Comment by pspeed42** [comment]
Not just "could be"... but it would be better separate.  There is no way a game networking API is ever going to be as efficient at streaming large files to a lot of clients as a web server is.  That is their job, after all.
