### ISSUE TITLE
Are you going to port jme3 sdk to gradle? 

### ISSUE THREAD

**Issue by xahon** [jMonkeyEngine/jmonkeyengine#869]
Hello. I'm having troubles with compiling gradle-based project on Android (honestly, I can't understand how to do it at all). Do you plan to make something similar to libgdx system? In libgdx you can run your application on Android very easy using adb, but in jme3 I can't

Ps. I don't use sdk and use idea instead

**Comment by grizeldi** [comment]
There were attempts to add the gradle plugin to the sdk and have default template based on gradle, but that didn't work out, don't exactly remember why anymore. Maybe @MeFisto97 can tell you more.

**Comment by xahon** [comment]
Thanks, @grizeldi. I hope @MeFisto94 will tell more in this thread

**Comment by MeFisto94** [comment]
I don't completely understand what you are looking for, so I'll explain everything:
"Back then" the SDK was built using custom ANT Tasks for jME users. Those are handling packaging your applications etc. Today gradle is the bee's knees, which is why no one wants ant anymore (though it still works actually).

The Problem is the SDK is subclassing Netbeans "Project" class, which the gradle plugin also does. This means you can either have the SDK Tools or the Gradle Project Thing.

I tried to integrate the both of them but I couldn't even add the gradle plugin as a dependency to a sdk netbeans module. I chatted with both the gradle plugin author as well as with the maintainers of netbeans but no one had a clue. I hope that with Netbeans 9.0 they have time again to look at this. If not, I'd need to merge the whole sourcecode into our code base, which is something I don't want to do, it's a maintenance hell.

The other dimension is the NbAndroid Module, which brought Android compatibility to Netbeans. In addition to that we had some custom Android Code. Unfortunately Android switched to gradle as well and changed their toolings, which is why the SDK currently is unable to build to Android (NbAndroidModule used ant and I _think_ it isn't updated anymore) and the SDK used android.bat to handle the AVM images and all. Since android.bat has been replaced and the syntax is completely different and more complex this should been redone completely.

Actually for Android I think you really profit from using Android Studio (which is IntelliJ), since it's generally built around Android, has a great UI Builder with Android in mind and all that which you would probably be missing in the SDK.


WORKAROUND 1
The Workaround I am currently using is having an old regular sdk project and adding a build.gradle (but NOT enabling the Gradle Plugin in the SDK). That way you can use the SDK as regular and I simply use the command line to launch my code. You only have the Problem that you need to add the libraries from maven manually to the SDK Project for the error highlighting to be satisfied.

I'm using these Gradle Tasks to support Debugging from within the SDK and Profiling (It will tell you the path to the .so/.dll inside Netbeans)
```gradle
task(debug, dependsOn: 'classes', type: JavaExec) {
    main = mainClassName
    classpath = sourceSets.main.runtimeClasspath
    jvmArgs = ["-Xdebug", "-Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=5005"]
}

task(profile, dependsOn: 'classes', type: JavaExec) {
	main = mainClassName
	classpath = sourceSets.main.runtimeClasspath
	
	jvmArgs = ['-XX:+UseLinuxPosixThreadCPUClocks', "-agentpath:/home/marc/Dokumente/02_GIT/sdk/build/testuserdir/lib/deployed/jdk16/linux-amd64/libprofilerinterface.so=/home/marc/Dokumente/02_GIT/sdk/build/testuserdir/lib,5140"]
}

task(profileJMC, dependsOn: 'classes', type: JavaExec) {
    main = mainClassName
    classpath = sourceSets.main.runtimeClasspath
    
    jvmArgs = ['-XX:+UnlockCommercialFeatures', '-XX:+FlightRecorder']
}
```

WORKAROUND 2:
This is much like Workaround 1, however you don't use the SDK to run things, you just use it to convert and edit models and then code in another IDE.

WORKAROUND 3:
There is the "jMonkeyBuilder", an Application designed to do tasks like Model Converting, Inspection, Material editing etc just like the SDK does. It also comes with an IntelliJ Plugin

**Comment by oxplay2** [comment]
My workaround is:

Create Ant project for just Assets
Create gradle project for sources/libs/etc.
in gradle dependencies add:
runtime files("..//separateAntAssetsProject/assets")
Ready! Just Use SDK features for all Assets, while still same SDK you can modify gradle project.

**Comment by MeFisto94** [comment]
Actually we're working on it at https://github.com/jMonkeyEngine/sdk/tree/gradle-support, but it didn't work to an almost unsolveable problem on the Netbeans side.
That being said, for Android I recommend using AndroidStudio anyway, as that has all the tools needed for the task.

You can share the project much like @oxplay2 recommends or even have multiple folders and just copy and paste here and there.
