### ISSUE TITLE
Patch for /trunk/engine/src/blender/com/jme3/scene/plugins/blender/materials/MaterialContext.java

### ISSUE THREAD

**Issue by ghost** [jMonkeyEngine/jmonkeyengine#98]
Reference on googlecode: https://code.google.com/p/jmonkeyengine/issues/detail?id=600

**Comment by Virepri** [comment]
This is the kind of thing you make a fork and then create a pull request for.

**Comment by MeFisto94** [comment]
# bump
How about implementing this, @jmekaelthas, or is it already implemented?

**Comment by jmekaelthas** [comment]
@MeFisto94  no, it is not yet implemented. I'll check it out and apply the patch if it does not break anything.

**Comment by jmekaelthas** [comment]
@MeFisto94 
I have looked inside the code and looks like there is no need to change anything. The 'spec' is applied on each type of the specular color of the material. But if you know that some colors import badly please provide me the blend file and I'll take a look at it.

**Comment by MeFisto94** [comment]
@jmekaelthas: To be honest, I didn't really look into the patch, I was just looking for some Issues I could create a PR for and thought this is an easy one for you to either apply or close.

Looking into the patch, it only differs by the "0.5f" (What were they ment for? They aren't there in master).
Also looking into https://github.com/jMonkeyEngine/jmonkeyengine/blob/master/jme3-blender/src/main/java/com/jme3/scene/plugins/blender/materials/MaterialContext.java#L322 this has been changed since ages and is independant of the specularity-type anyway.

So if you have the powers, you can close this :)
